version: "3.9"

services:
  front:
    build: ./frontend
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    #command: ["serve", "-s", "build"]
    
  back:
    build: ./backend
    container_name: back
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/backend
    command: ["python3", "./manage.py", "runserver"]

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back