version: "3.9"

services:
  front:
    build: ./frontend
    container_name: front
    expose:
      - "3000"
    volumes:
      - ./frontend:/frontend
    command: ["npm", "start"]
  
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - "27019"
    volumes:
      - ./mongo/data:/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "IBK"
      MONGO_INITDB_ROOT_PASSWORD: "1234"

  back:
    build: ./backend
    container_name: back
    expose:
      - "4000"
    volumes:
      - ./backend:/backend
    command: ["python3", "./manage.py", "runserver", "0.0.0.0:4000"]
    tty: true
    depends_on:
      - mongo

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back
      - mongo